[env]
TERM = "xterm-256color"

[font]
size = 19
normal = { family = "Google Sans Code", style = "Light" }
bold = { family = "Google Sans Code", style = "Regular" }
italic = { family = "Google Sans Code", style = "Light Italic" }
bold_italic = { family = "Google Sans Code", style = "Italic" }
offset = { y = 8 }
glyph_offset = { y = 4 }

[window]
dynamic_padding = true
decorations = "Buttonless"
padding = { x = 10, y = 10 }
opacity = 0.9
blur = true

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/theme.toml"
]
